stages:
    - deploy

deploy:
    stage: deploy
    image: ubuntu:18.04
    before_script:
      - apt-get update -qy
      - apt-get install -y lftp
    script:
      - echo $FTP_ADDRESS
      - lftp -e "open $FTP_ADDRESS; user $FTP_USER $FTP_PASSWORD; cd domains; mirror -X .* -X .*/ --reverse --verbose --delete ./froom/dist/ domains/$FTP.USER.$FTP_ADDRESS/; bye"