stages:
    - deploy

build:
  stage: build
  image: node:latest
  script:
    - cd froom
    - npm install
    - npm run build
  artifacts:
    paths:
      - froom/dist/

deploy:
    stage: deploy
    image: mwienk/docker-lftp
    script:
      - docker run -it mwienk/docker-lftp lftp --help