image: docker:latest

services:
- docker:dind

before_script:
- docker version
- chkconfig docker on

stages:
    - build

build:
  stage: build
  script:
    - cd froom
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
