stages:
  - build
#  - deploy

build web-api:
  stage: build
  image: mcr.microsoft.com/dotnet/core/sdk:3.1.200-buster-arm32v7
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - cd ./WebAPI
    - dotnet restore "WebAPI/WebAPI.csproj"
    - dotnet build "WebAPI/WebAPI.csproj" -c Release
    - dotnet publish "WebAPI/WebAPI.csproj" -c Release
  artifacts:
    paths:
      - WebAPI/WebAPI/bin/Release/
    