stages:
  - build
  - deploy
  
build web-api:
  stage: build
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  script:
    - cd ./WebAPI
    - dotnet restore "WebAPI/WebAPI.csproj"
    - dotnet build "WebAPI/WebAPI.csproj" -c Release
    - dotnet publish "WebAPI/WebAPI.csproj" -c Release
  artifacts:
    paths:
      - WebAPI/WebAPI/bin/Release/
    expire_in: 1 week
      
build vue:
  stage: build
  image: node:latest
  script:
    - cd  WebAPI/WebAPI/vue
    - npm install
    - npm run build
    
  artifacts:
    paths:
      - WebAPI/WebAPI/vue/dist/
    expire_in: 1 week

deploy:
    stage: deploy
    image: alpine:3.7
    only:
        - master
        - develop
    before_script:
        - apk add lftp
    script:
        - lftp -e "rm -rf /domains/${FTP_DOMAIN}; mkdir /domains/${FTP_DOMAIN}; exit" -u $FTP_USER,$FTP_PASSWORD $FTP_ADDRESS
        - lftp -e "mirror --verbose --reverse --no-perms WebAPI/WebAPI/bin/Release/netcoreapp3.1/publish/ domains/$FTP_DOMAIN/; exit" -u $FTP_USER,$FTP_PASSWORD $FTP_ADDRESS
        - lftp -e "mirror --verbose --reverse --no-perms WebAPI/WebAPI/vue/dist/ domains/$FTP_DOMAIN/vue/dist; exit" -u $FTP_USER,$FTP_PASSWORD $FTP_ADDRESS
        