stages:
  - build
#  - deploy
build web-api:
  stage: build
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  script:
    - cd ./WebAPI
    - dotnet restore "WebAPI/WebAPI.csproj"
    - dotnet build "WebAPI/WebAPI.csproj" -c Release
    - dotnet publish "WebAPI/WebAPI.csproj" -c Release
  artifacts:
    paths:
      - WebAPI/WebAPI/bin/Release/
      
build vue:
  stage: build
  image: node:latest
  script:
    - cd  WebAPI/WebAPI/vue
    - npm install
    - npm run build
  artifacts:
    paths:
      - froom/vue/dist/

#deploy web-api:
#    stage: deploy
#    image: ubuntu:18.04
#    only:
 #       - master
#        - develop
#    before_script:
#        - apt-get update -qy
#        - apt-get install -y lftp
#        - apt-get install ca-certificates -y
#    script:
#        - update-ca-certificates
#        - lftp -e "open $FTP_ADDRESS; user $FTP_USER $FTP_PASSWORD;""
#        - lftp -e "mirror -p -X .* -X .*/ --reverse --verbose --delete .WebAPI/WebAPI/bin/Release/ domains/$FTP_USER.$FTP_ADDRESS/;"
#        - lftp -e "mirror -p -X .* -X .*/ --reverse --verbose --delete ./froom/vue/dist/ domains/$FTP_USER.$FTP_ADDRESS/vue/dist; bye"