stages:
    - build
    - deploy

build web-api:
  stage: build
  image: docker
  script:
    - cd froom/WebAPI
    - msbuild Froom.sln
  artifacts:
    paths:
      - froom/

build vue:
  stage: build
  image: node:latest
  script:
    - cd froom/vue
    - npm install
    - npm run build
  artifacts:
    paths:
      - froom/dist/

deploy web-api:
    stage: deploy
    script:
      - echo "deploying"
    only:
      - master
      - develop

deploy vue:
    stage: deploy
    image: ubuntu:18.04
    only:
      - master
      - develop
    before_script:
      - apt-get update -qy
      - apt-get install -y lftp
      - apt-get install ca-certificates -y
    script:
      - update-ca-certificates
      - lftp -e "open $FTP_ADDRESS; user $FTP_USER $FTP_PASSWORD; mirror -p -X .* -X .*/ --reverse --verbose --delete ./froom/dist/ domains/$FTP_USER.$FTP_ADDRESS/; bye"