stages:
    - build
    - deploy

build:
  image: node:latest
  script:
    - cd froom
    - npm install
    - npm run build
  artifacts:
    paths:
      - froom/dist/

deploy:
    image: ustcmirror/lftpsync:latest
    script:
      - lftp