image: node:latest

stages:
    - build

build:
  stage: build
  before_script:
    - apt-get install lftp
  script:
    - cd froom
    - npm install
    - npm run build
  artifacts:
    paths:
      - froom/dist/
