image: node:latest

stages:
    - build

build:
  stage: build
  script:
    - echo $CI_JOB_STAGE
    - echo $VENUS_PASSWORD
    - cd froom
    - npm install
    - npm run build
  artifacts:
    paths:
      - froom/dist/
