stages:
    - build
    - deploy

build:
  stage: build
  image: node:latest
  script:
    - cd froom
    - npm install
    - npm run build
  artifacts:
    paths:
      - froom/dist/

deploy:
    stage: deploy
    image: ubuntu:18.04
    before_script:
      - apt-get update -qy
      - apt-get install -y lftp
      - apt-get install ca-certificates -y
    script:
      - update-ca-certificates
      - lftp -e "open $FTP_ADDRESS; user $FTP_USER $FTP_PASSWORD; cd domains; mirror -X .* -X .*/ --reverse --verbose --delete ./froom/dist/ domains/$FTP_USER.$FTP_ADDRESS/; bye"